# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from fusion_simulation.service.proto import (
    simulation_pb2 as fusion__simulation_dot_service_dot_proto_dot_simulation__pb2,
)

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fusion_simulation/service/proto/simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/fusion_simulation.SimulationService/Init',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.InitRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/fusion_simulation.SimulationService/Step',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StepRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/fusion_simulation.SimulationService/Reset',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.ResetRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/fusion_simulation.SimulationService/GetStatus',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StatusRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/fusion_simulation.SimulationService/StreamEvents',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.EventResponse.FromString,
                _registered_method=True)
        self.LoadScene = channel.unary_unary(
                '/fusion_simulation.SimulationService/LoadScene',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.LoadSceneRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.LoadSceneResponse.FromString,
                _registered_method=True)
        self.SaveSnapshot = channel.unary_unary(
                '/fusion_simulation.SimulationService/SaveSnapshot',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SaveSnapshotRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SaveSnapshotResponse.FromString,
                _registered_method=True)
        self.RestoreSnapshot = channel.unary_unary(
                '/fusion_simulation.SimulationService/RestoreSnapshot',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.RestoreSnapshotRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.RestoreSnapshotResponse.FromString,
                _registered_method=True)
        self.StreamSensorData = channel.unary_stream(
                '/fusion_simulation.SimulationService/StreamSensorData',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StreamSensorDataRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SensorDataResponse.FromString,
                _registered_method=True)
        self.StreamSimState = channel.stream_stream(
                '/fusion_simulation.SimulationService/StreamSimState',
                request_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SimStateRequest.SerializeToString,
                response_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SimStateResponse.FromString,
                _registered_method=True)


class SimulationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSimState(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.InitRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.InitResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StepRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StepResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.ResetRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.ResetResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StatusRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StatusResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StreamEventsRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.EventResponse.SerializeToString,
            ),
            'LoadScene': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadScene,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.LoadSceneRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.LoadSceneResponse.SerializeToString,
            ),
            'SaveSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSnapshot,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SaveSnapshotRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SaveSnapshotResponse.SerializeToString,
            ),
            'RestoreSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreSnapshot,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.RestoreSnapshotRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.RestoreSnapshotResponse.SerializeToString,
            ),
            'StreamSensorData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StreamSensorDataRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SensorDataResponse.SerializeToString,
            ),
            'StreamSimState': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSimState,
                    request_deserializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SimStateRequest.FromString,
                    response_serializer=fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SimStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fusion_simulation.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fusion_simulation.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/Init',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.InitRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/Step',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StepRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/Reset',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.ResetRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/GetStatus',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StatusRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fusion_simulation.SimulationService/StreamEvents',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StreamEventsRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/LoadScene',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.LoadSceneRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.LoadSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/SaveSnapshot',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SaveSnapshotRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SaveSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion_simulation.SimulationService/RestoreSnapshot',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.RestoreSnapshotRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.RestoreSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fusion_simulation.SimulationService/StreamSensorData',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.StreamSensorDataRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SensorDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSimState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fusion_simulation.SimulationService/StreamSimState',
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SimStateRequest.SerializeToString,
            fusion__simulation_dot_service_dot_proto_dot_simulation__pb2.SimStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
